USE [SUPREMO_M8_Supremo_Sistemas]
GO

/****** Object:  View [dbo].[rel_documentos_fiscais]    Script Date: 21/08/2023 10:44:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* Synchronization script for SQL-02.M8SISTEMAS.COM.BR,1433.BASE_Implantacao_Empresas_Normais
 Generated by SQL Delta on 19/05/2023 10:23:06
 Please backup BASE_Implantacao_Empresas_Normais before executing this script
 */
CREATE VIEW [dbo].[rel_documentos_fiscais]
AS
SELECT        dbo.documentos_fiscais.id, dbo.documentos_fiscais.nr_documento, dbo.documentos_fiscais.tipo_documento, dbo.documentos_fiscais.status, dbo.documentos_fiscais.documento, dbo.documentos_fiscais.nr_documento_nfe, 
                         dbo.documentos_fiscais.data_emissao, dbo.documentos_fiscais.chave_nfe, dbo.documentos_fiscais.valor_acrescimo, dbo.documentos_fiscais.valor_desconto, dbo.documentos_fiscais.valor_frete, 
                         dbo.documentos_fiscais.valor_frete_pagar, dbo.documentos_fiscais.valor_seguro, dbo.documentos_fiscais.pessoa_id, dbo.documentos_fiscais.empresa_id, dbo.documentos_fiscais.transportador_id, 
                         dbo.documentos_fiscais.frete_id, dbo.documentos_fiscais.sintegra_id, dbo.documentos_fiscais.condicao_pagamento_id, dbo.documentos_fiscais.serie_documento_id, dbo.documentos_fiscais.especie_volume, 
                         dbo.documentos_fiscais.marca_volume, dbo.documentos_fiscais.observacao, dbo.documentos_fiscais.peso_bruto, dbo.documentos_fiscais.peso_liquido, pessoa.razao_social AS pessoa_razao_social, 
                         pessoa.fantasia AS pessoa_fantasia, pessoa.cpf_cnpj AS pessoa_cpf_cnpj, empresa.razao_social AS empresa_razao_social, empresa.fantasia AS empresa_fantasia, empresa.cpf_cnpj AS empresa_cpf_cnpj, 
                         transportador.razao_social AS transportador_razao_social, transportador.fantasia AS transportador_fantasia, transportador.cpf_cnpj AS transportador_cpf_cnpj, dbo.pessoas_enderecos.logradouro AS pessoa_logradouro, 
                         dbo.pessoas_enderecos.cep AS pessoa_cep, dbo.pessoas_enderecos.numero AS pessoa_numero, dbo.pessoas_enderecos.letra AS pessoa_letra, dbo.pessoas_enderecos.complemento AS pessoa_complemento, 
                         dbo.pessoas_enderecos.caixa_postal AS pessoa_caixa_postal, pessoa_bairros.nome AS pessoa_bairro, pessoa_municipios.nome AS pessoa_municipio, pessoa_estados.nome AS pessoa_estado, 
                         pessoa_estados.uf AS pessoa_uf, dbo.pessoas_enderecos.tipo_endereco AS pessoa_tipo_endereco, pessoa_bairros.id AS pessoa_bairro_id, pessoa_municipios.id AS pessoa_municipio_id, 
                         pessoa_bairros.id AS pessoa_estado_id, pessoa.telefone AS pessoa_telefone, pessoa.celular AS pessoa_celular, pessoa.email AS pessoa_email, pessoa.inscricao_municipal AS pessoa_inscricao_municipal, 
                         pessoa.inscricao_estadual AS pessoa_inscricao_estadual, pessoa.rg AS pessoa_rg, dbo.prazos_entregas.nome AS prazo_entrega, dbo.documentos_fiscais.impostos, empresa_enderecos.logradouro AS empresa_logradouro, 
                         empresa_enderecos.cep AS empresa_cep, empresa_enderecos.numero AS empresa_numero, empresa_enderecos.letra AS empresa_letra, empresa_enderecos.complemento AS empresa_complemento, 
                         empresa_enderecos.caixa_postal AS empresa_caixa_postal, empresa_municipios.nome AS empresa_municipio, empresa_estados.nome AS empresa_estado, empresa_estados.uf AS empresa_uf, 
                         dbo.bairros.nome AS empresa_bairro, empresa_enderecos.tipo_endereco AS empresa_tipo_endereco, dbo.bairros.id AS empresa_bairro_id, empresa_municipios.id AS empresa_municipio_id, 
                         dbo.bairros.id AS empresa_estado_id, empresa.telefone AS empresa_telefone, empresa.inscricao_estadual AS empresa_inscricao_estadual, empresa.email AS empresa_email, empresa.site AS empresa_site, 
                         dbo.documentos_fiscais.data_inicio, dbo.documentos_fiscais.data_fim, dbo.documentos_fiscais.contato, dbo.documentos_fiscais.telefone_contato AS contato_telefone, dbo.documentos_fiscais.valor_total_geral, 
                         dbo.documentos_fiscais.valor_total_geral_produtos, dbo.documentos_fiscais.valor_total_geral_servicos, dbo.documentos_fiscais.valor_total_geral_desconto_itens, 
                         dbo.documentos_fiscais.valor_total_geral_desconto_produtos, dbo.documentos_fiscais.valor_total_geral_desconto_servicos, 
                         dbo.documentos_fiscais.valor_total_geral_desconto_itens + dbo.documentos_fiscais.valor_desconto AS valor_total_geral_desconto, funcionario.razao_social AS funcionario_razao_social, 
                         funcionario.fantasia AS funcionario_fantasia, dbo.documentos_fiscais.funcionario_id, dbo.documentos_fiscais.atendente_id, atendente.razao_social AS atendente_razao_social, atendente.fantasia AS atendente_fantasia, 
                         dbo.documentos_fiscais.serie AS serie_nf, dbo.documentos_fiscais.sub_serie, dbo.documentos_fiscais.especie_documento, dbo.documentos_fiscais.especie_id, dbo.documentos_fiscais.moeda_id, 
                         dbo.condicoes_pagamentos.nome AS condicoes_pagamentos_nome, dbo.moedas.nome AS moedas_nome, dbo.financeiro_especies.nome AS especie_financeiro_nome, dbo.documentos_fiscais.tipo_compra_id, 
                         dbo.tipos_compras.nome AS tipo_compra_nome, dbo.documentos_fiscais.data_cadastro, dbo.documentos_fiscais.data_lancamento, dbo.documentos_fiscais.usuario_atualizacao_id, 
                         dbo.documentos_fiscais.usuario_cadastro_id, usuario_atualizacao.nome AS usuario_atualizacao_nome, usuario_cadastro.nome AS usuario_cadastro_nome, dbo.documentos_fiscais.contrato_id, 
                         '' AS codigo_especificador_cest, dbo.veiculos_pessoas.placa AS veiculo_placa, dbo.veiculos_pessoas.ano_fabricacao AS veiculo_ano_fabricacao, dbo.veiculos_pessoas.ano_modelo AS veiculo_ano_modelo, 
                         dbo.veiculos_pessoas.cor AS veiculo_cor, dbo.veiculos_pessoas.combustivel AS veiculo_combustivel, dbo.veiculos_pessoas.marca_modelo AS veiculo_modelo, dbo.veiculos_pessoas.chassi AS veiculo_chassi, 
                         dbo.veiculos_pessoas.renavam AS veiculo_renavam, dbo.documentos_fiscais.id_origem_dados, dbo.documentos_fiscais.outros_documentos_operacao_id, 
                         dbo.outros_documentos_operacoes.nome AS outros_documentos_operacao_nome, dbo.outros_documentos_operacoes.tipo_operacao AS outros_documentos_operacao_tipo, ger.nome AS desc_equipamento, 
                         ger.apelido AS desc_equipamento_apelido, eq_pess.modelu AS modelo_motor, eq_pess.numero_motor, eq_pess.numero_chassi AS modelo_gerador, eq_pess.compressor AS numero_gerador, 
                         eq_pess.capacidade_nominal AS potencia, eq_pess.bateria AS tensao, eq_pess.numero_transmissao AS quadro_comando, eq_pess.numero_diferencial AS contactor, eq_pess.serie
FROM            dbo.pessoas AS funcionario RIGHT OUTER JOIN
                         dbo.pessoas_enderecos AS empresa_enderecos INNER JOIN
                         dbo.pessoas AS empresa ON empresa_enderecos.pessoa_id = empresa.id INNER JOIN
                         dbo.municipios AS empresa_municipios ON empresa_enderecos.municipio_id = empresa_municipios.id INNER JOIN
                         dbo.estados AS empresa_estados ON empresa_municipios.estado_id = empresa_estados.id INNER JOIN
                         dbo.bairros ON empresa_enderecos.bairro_id = dbo.bairros.id RIGHT OUTER JOIN
                         dbo.pessoas AS pessoa INNER JOIN
                         dbo.documentos_fiscais ON pessoa.id = dbo.documentos_fiscais.pessoa_id LEFT OUTER JOIN
                         dbo.veiculos_pessoas ON dbo.documentos_fiscais.veiculo_id = dbo.veiculos_pessoas.id ON empresa.id = dbo.documentos_fiscais.empresa_id LEFT OUTER JOIN
                         dbo.usuarios AS usuario_cadastro ON dbo.documentos_fiscais.usuario_cadastro_id = usuario_cadastro.id ON funcionario.id = dbo.documentos_fiscais.funcionario_id LEFT OUTER JOIN
                         dbo.pessoas AS transportador ON dbo.documentos_fiscais.transportador_id = transportador.id LEFT OUTER JOIN
                         dbo.pessoas AS atendente ON dbo.documentos_fiscais.atendente_id = atendente.id LEFT OUTER JOIN
                         dbo.tipos_compras ON dbo.documentos_fiscais.tipo_compra_id = dbo.tipos_compras.id LEFT OUTER JOIN
                         dbo.financeiro_especies ON dbo.documentos_fiscais.especie_id = dbo.financeiro_especies.id LEFT OUTER JOIN
                         dbo.moedas ON dbo.documentos_fiscais.moeda_id = dbo.moedas.id LEFT OUTER JOIN
                         dbo.condicoes_pagamentos ON dbo.documentos_fiscais.condicao_pagamento_id = dbo.condicoes_pagamentos.id LEFT OUTER JOIN
                         dbo.bairros AS pessoa_bairros INNER JOIN
                         dbo.pessoas_enderecos ON pessoa_bairros.id = dbo.pessoas_enderecos.bairro_id INNER JOIN
                         dbo.municipios AS pessoa_municipios ON pessoa_bairros.municipio_id = pessoa_municipios.id INNER JOIN
                         dbo.estados AS pessoa_estados ON pessoa_municipios.estado_id = pessoa_estados.id ON pessoa.id = dbo.pessoas_enderecos.pessoa_id LEFT OUTER JOIN
                         dbo.prazos_entregas ON dbo.documentos_fiscais.prazo_entrega_id = dbo.prazos_entregas.id LEFT OUTER JOIN
                         dbo.usuarios AS usuario_atualizacao ON dbo.documentos_fiscais.usuario_atualizacao_id = usuario_atualizacao.id LEFT OUTER JOIN
                         dbo.outros_documentos_operacoes ON dbo.documentos_fiscais.outros_documentos_operacao_id = dbo.outros_documentos_operacoes.id LEFT OUTER JOIN
                         dbo.equipamento_pessoa AS eq_pess ON eq_pess.pessoa_id = pessoa.id LEFT OUTER JOIN
                         dbo.produtos AS ger ON ger.id = eq_pess.equipamento_id
WHERE        (dbo.pessoas_enderecos.tipo_endereco = 1) AND (dbo.documentos_fiscais.excluido = 'false') AND (dbo.pessoas_enderecos.excluido = 'false') AND (empresa_enderecos.tipo_endereco = 1) AND 
                         (empresa_enderecos.excluido = 'false')
GO

EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[46] 4[14] 2[24] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "funcionario"
            Begin Extent = 
               Top = 45
               Left = 415
               Bottom = 175
               Right = 696
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "empresa_enderecos"
            Begin Extent = 
               Top = 41
               Left = 184
               Bottom = 185
               Right = 441
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "empresa"
            Begin Extent = 
               Top = 218
               Left = 409
               Bottom = 348
               Right = 690
            End
            DisplayFlags = 280
            TopColumn = 3
         End
         Begin Table = "empresa_municipios"
            Begin Extent = 
               Top = 402
               Left = 38
               Bottom = 532
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 1
         End
         Begin Table = "empresa_estados"
            Begin Extent = 
               Top = 534
               Left = 38
               Bottom = 664
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "bairros"
            Begin Extent = 
               Top = 666
               Left = 38
               Bottom = 796
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "pessoa"
            Begin Extent = 
               Top = 798
               Left = 38
               Bottom = 928
               Right = 319
            End' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'rel_documentos_fiscais'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "documentos_fiscais"
            Begin Extent = 
               Top = 930
               Left = 38
               Bottom = 1060
               Right = 325
            End
            DisplayFlags = 280
            TopColumn = 16
         End
         Begin Table = "veiculos_pessoas"
            Begin Extent = 
               Top = 1062
               Left = 38
               Bottom = 1192
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "usuario_cadastro"
            Begin Extent = 
               Top = 1194
               Left = 38
               Bottom = 1324
               Right = 322
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "transportador"
            Begin Extent = 
               Top = 1326
               Left = 38
               Bottom = 1456
               Right = 319
            End
            DisplayFlags = 280
            TopColumn = 70
         End
         Begin Table = "atendente"
            Begin Extent = 
               Top = 1458
               Left = 38
               Bottom = 1588
               Right = 319
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "tipos_compras"
            Begin Extent = 
               Top = 1590
               Left = 38
               Bottom = 1720
               Right = 367
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "financeiro_especies"
            Begin Extent = 
               Top = 1722
               Left = 38
               Bottom = 1852
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "moedas"
            Begin Extent = 
               Top = 1854
               Left = 38
               Bottom = 1984
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "condicoes_pagamentos"
            Begin Extent = 
               Top = 1986
               Left = 38
               Bottom = 2116
               Right = 306
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "pessoa_bairros"
            Begin Extent = 
               Top = 2118
               Left = 38
               Bottom = 2248
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "pessoas_enderecos"
            Begin Extent = 
               Top = 2250
               Left = 38
               Bottom = 2380
               Right = 295
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "pessoa_municipios"
            Begin Extent = 
               Top = 2382
               Left = 38
               Bottom = 2512
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "pessoa_estados"
            Begin Extent = 
               Top = 2514
               Left = 38
               Bottom = 2644
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "prazos_entregas"
            Begin Extent = 
               Top = 2646
               Left = 38
               B' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'rel_documentos_fiscais'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane3', @value=N'ottom = 2776
               Right = 245
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "usuario_atualizacao"
            Begin Extent = 
               Top = 2778
               Left = 38
               Bottom = 2908
               Right = 322
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "outros_documentos_operacoes"
            Begin Extent = 
               Top = 2910
               Left = 38
               Bottom = 3040
               Right = 367
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "eq_pess"
            Begin Extent = 
               Top = 6
               Left = 734
               Bottom = 136
               Right = 955
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "ger"
            Begin Extent = 
               Top = 138
               Left = 734
               Bottom = 268
               Right = 996
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 4890
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'rel_documentos_fiscais'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=3 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'rel_documentos_fiscais'
GO

